version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python app.py && flask db init && flask db migrate && flask db upgrade"
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=main-microservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - .dbdata:/var/lib/postgres

volumes:
  .dbdata: